name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  toast: ^0.1.5
  flutter_markdown: ^0.2.0
  english_words: ^3.1.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

